### ISSUE TITLE
Creation of gridfile, option 2/3

### ISSUE THREAD

**Issue by mvhulten** [HPSCTerrSys/eCLM_static_file_workflow#6]
The *ESMF-Mesh* method depends on [this script](https://github.com/ESCOMP/CTSM/blob/master/python/ctsm/mesh_maker.py) but modified.

@chartick introduced the README (as `curvilinear_docu.md`) in Feb 2023, where he wrote
> A solution to create them is again found in a CTSM branch: `subset_mesh_dask` under `tools/site_and_regional/mesh_maker.py`

This branch does not exist (anyore) in the mentioned CTSM repo, and all branches contain the same version of `mesh_maker.py`.

> [@chartick] had to rewrite part of the script for it to accept 2d lat / lon.

Is this still available somewhere?

(**edit:** fixed the path to the original `mesh_maker.py`—a wrapper script was introduced in the CTSM repo and the original `mesh_maker.py` moved, but still the modified one is not available in any of the branches, but see comment of Carl below)

**Comment by chartick** [comment]
Hi,
they indeed really overhauled the CTSM repro it seems. They had so many
branches before...

Anyway, my old documentation is not ideal but the script I am talking about
is here:

https://github.com/HPSCTerrSys/eCLM_static_file_workflow/blob/main/mkmapgrids/scrip_mesh.py



Marco van Hulten ***@***.***> schrieb am Mi., 6. Nov. 2024,
15:00:

**Comment by mvhulten** [comment]
This does not work:
```sh
/p/project1/cdetect/vanhulten1/setups/eCLM_static_file_workflow/mkmapgrids/scrip_mesh.py --ifile=/p/largedata2/detectdata/CentralDB/projects/z04/detect_grid_specs/grids/EUR-R13B05_199920_grid_inclbrz_v2.nc --ofile=out.nc
```
because the input file has no variable `lat`.
It has `clat`, `vlat` and `elat`.
I suppose `clat` is the centre of the grid box (and I will assume we are on a C grid).

Just to see what happens, I replaced all `lat` entries in the script for `clat`, but now it complains that the *input file does not have variable named clat*, even though it does (it's a double of dimension `cell=199920`).

**Comment by chartick** [comment]
This seems to be an ICON-grid which is a special case. There is an extra script for that: https://github.com/HPSCTerrSys/eCLM_static_file_workflow/blob/main/mkmapgrids/ICON_SCRIP.py

Please also look at the parts about ICON in the README. 

You also do not have to change the coordinate name in scrip_mesh.py it can be handed over as a command line arguement. However it does not work for `ICON_SCRIP.py`

**Comment by mvhulten** [comment]
This is fixed in an upcoming merge request.
